Controllers/ContactController.cs
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Davinci.Models.ReCaptcha;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace Davinci.Controllers
{
    public class ContactController : Controller
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Contact(string name, string phone, string message, string recaptcha)
        {
            if (!await IsHuman(recaptcha))
            {
                return Ok("bot");
            }

            var status = await SendMail("Связь с дирекцией", name + ", " + phone + "\n" + message);

            return status ? Ok("ok") : Ok("error");
        }

        private async Task<bool> SendMail(string subject, string message)
        {
            const string apiKey = "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";

            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("robot.native@gmail.com");
            var to = new EmailAddress("davinci.vrn@gmail.com");
            var msg = MailHelper.CreateSingleEmail(from, to, subject, message, "");
            var response = await client.SendEmailAsync(msg);

            return response.StatusCode == HttpStatusCode.Accepted;
        }

        private static async Task<bool> IsHuman(string recaptcha)
        {
            const string uri = "https://www.google.com/recaptcha/api/siteverify";

            var request = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("secret", "6LdSWv8UAAAAAJDJd3iovaoj2TnHC03mMrHgzI5B"),
                new KeyValuePair<string, string>("response", recaptcha),
            });

            var httpClient = new HttpClient();
            var result = await httpClient.PostAsync(uri, request);

            // Если гугл не работает, считаем что капча пройдена
            if (result.StatusCode != HttpStatusCode.OK) return true;

            var content = await result.Content.ReadAsStringAsync();
            var response = JsonConvert.DeserializeObject<ResponseV3>(content);

            return response.Success && response.Score > 0.5;
        }
    }
}

Views/Shared/Partial/_Footer.cshtml
@inject Davinci.Services.MedicalAidService MedicalAidService

@{
    var hierarchy = await MedicalAidService.GetAidHierarchy();
    var childs = new List<Piranha.Data.Page>();

    foreach (var (key, value) in hierarchy)
    {
        childs.AddRange(value);
    }
}

<footer class="site-footer">
    <div class="site-footer__title">© 2022 DaVinci - Искусство стоматологии</div>
    
    <div class="footer-services">
        @foreach (var child in childs)
        {
            <a href="/@child.Slug" class="footer-services__item">
                @child.Title
            </a>
        }
    </div>

    <div class="site-footer__social-links social-links">
        <ul>
            <li><a href="https://vk.com/club137762144" target="_blank"><i class="fab fa-vk"></i></a></li>
        </ul>
    </div>
</footer>

Views/Shared/Partial/_Menu.cshtml
@inject Davinci.Services.MedicalAidService MedicalAidService

@{
    var sitemap = WebApp.Site.Sitemap;
    var hierarchy = await MedicalAidService.GetAidHierarchy();
    var aidRoot = await MedicalAidService.GetAidRoot();
}

<nav class="menu">
    <ul class="">
        @foreach (var item in sitemap)
        {
            <li class="menu__item @(item.Id == WebApp.PageId ? "menu__item_active" : "")">
                <a class="menu__link" href="@item.Permalink"><span>@item.MenuTitle</span></a>
            </li>
        }
    </ul>
</nav>

<nav class="mobile-menu">
    <ul class="">
        @foreach (var item in sitemap)
        {
            <li class="mobile-menu__item @(item.Id == WebApp.PageId ? "menu__item_active" : "")">
                @if (item.Id == aidRoot.Id)
                {
                    <a class="mobile-menu__link show-expand" href="#">@item.MenuTitle</a>
                    <ul class="mobile-menu__expand-menu">
                        <li class="mobile-menu__item">
                            <a class="mobile-menu__link hide-expand">Назад</a>
                        </li>
                        @foreach (var pair in hierarchy)
                        {
                            <li class="mobile-menu__item">
                                <a href="#" class="mobile-menu__link show-expand">@pair.Key.Title</a>
                                <ul class="mobile-menu__expand-menu">
                                    <li class="mobile-menu__item">
                                        <a class="mobile-menu__link hide-expand">Назад</a>
                                    </li>
                                    @foreach (var child in pair.Value)
                                    {
                                        <li class="mobile-menu__item">
                                            <a href="/@child.Slug" class="mobile-menu__link @(child.Id == WebApp.PageId ? "mobile-menu__link_active" : "")">
                                                @child.Title
                                            </a>
                                        </li>
                                    }
                                </ul>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <a class="mobile-menu__link @(item.Id == WebApp.PageId ? "mobile-menu__link_active" : "")" href="@item.Permalink">@item.MenuTitle</a>
                }
            </li>
        }

        <li class="mobile-menu__item">
            <a class="mobile-menu__link" href="https://prodoctorov.ru/voronezh/lpu/60821-davinchi" target="_blank">Записаться на приём</a>
        </li>
        <li class="mobile-menu__item">
            <a class="mobile-menu__link" href="tel:+79518595522">Связь с дирекцией</a>
        </li>
    </ul>
</nav>

Views/Shared/Partial/_Meta.cshtml
@model IMeta

<meta name="keywords" content="@Model.MetaKeywords">
<meta name="description" content="@Model.MetaDescription">

<meta name="og:type" content="article">
<meta name="og:title" content="@Model.Title">
<meta name="og:description" content="@Model.MetaDescription">

Views/Shared/Partial/_Modal.cshtml
<div class="modal" id="modal-contact">
    <div class="modal__container">
        <div class="modal__close-action close-modal-contact">
            <img src="~/images/btn-close.svg"/>
        </div>

        <form asp-controller="Contact" asp-action="Contact" class="modal-content">
            <h2>Связь с дирекцией</h2>

            <h3>В данном разделе вы можете описать своё обращение, предложение, жалобу и дирекция клиники обязательно примет меры, при необходимости свяжется с вами.</h3>
            <h3>
                Также Вы можете позвонить директору клиники напрямую по телефону
                <br>
                    <b>+7 920 461 77 22</b>
                </br>
            </h3>

            <div class="modal-content__line">
                <input type="text" name="name" placeholder="Ваше имя"/>
                <input type="text" name="phone" placeholder="Телефон"/>
            </div>
            <div class="modal-content__message">
                <textarea name="message" placeholder="Ваше обращение"></textarea>
            </div>

            <input type="hidden" id="recaptcha-token" name="recaptcha"/>

            <div class="modal-content__actions">
                <button type="submit" class="btn-submit">Отправить</button>
                <div class="modal-content__disclaimer">
                    Нажимая на кнопку «Отправить», я даю согласие на обработку персональных данных и соглашаюсь с
                    <a href="/Privacy" target="_blank">политикой конфиденциальности</a>.
                </div>
            </div>
            <div class="modal-content__line">
                <span class="google-privacy">
                This site is protected by reCAPTCHA and the Google
                <a href="https://policies.google.com/privacy">Privacy Policy</a> and
                <a href="https://policies.google.com/terms">Terms of Service</a> apply.
                </span>
            </div>
        </form>
    </div>
</div>